CREATE TABLE IF NOT EXISTS public.user_activity_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid NOT NULL,
  event_type text NOT NULL,
  path text,
  metadata jsonb
);

CREATE INDEX IF NOT EXISTS user_activity_log_created_at_idx ON public.user_activity_log (created_at DESC);
CREATE INDEX IF NOT EXISTS user_activity_log_user_id_idx ON public.user_activity_log (user_id);

ALTER TABLE public.user_activity_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_activity_log_insert_own" ON public.user_activity_log;
CREATE POLICY "user_activity_log_insert_own"
  ON public.user_activity_log
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "user_activity_log_select_admin" ON public.user_activity_log;
CREATE POLICY "user_activity_log_select_admin"
  ON public.user_activity_log
  FOR SELECT
  TO authenticated
  USING (public.is_admin_user_safe());

