-- Retención de evidencia de inspecciones: hot (Supabase) -> cold (R2) -> deleted.
-- La fila de public.inspections nunca se elimina por esta política.

ALTER TABLE public.inspections
  ADD COLUMN IF NOT EXISTS storage_tier text NOT NULL DEFAULT 'hot',
  ADD COLUMN IF NOT EXISTS archived_at timestamptz,
  ADD COLUMN IF NOT EXISTS r2_pdf_path text,
  ADD COLUMN IF NOT EXISTS r2_pdf_retiro_path text,
  ADD COLUMN IF NOT EXISTS r2_photos jsonb NOT NULL DEFAULT '{"before_service":[],"client_vehicle":[],"equipment_used":[]}'::jsonb,
  ADD COLUMN IF NOT EXISTS archive_manifest jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'inspections_storage_tier_check'
      AND conrelid = 'public.inspections'::regclass
  ) THEN
    ALTER TABLE public.inspections
      ADD CONSTRAINT inspections_storage_tier_check
      CHECK (storage_tier IN ('hot', 'cold', 'deleted'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS inspections_retention_hot_idx
  ON public.inspections (created_at)
  WHERE storage_tier = 'hot';

CREATE INDEX IF NOT EXISTS inspections_retention_cold_idx
  ON public.inspections (archived_at)
  WHERE storage_tier = 'cold';

COMMENT ON COLUMN public.inspections.storage_tier IS 'hot=Supabase Storage, cold=Cloudflare R2, deleted=archivos eliminados por retención';
COMMENT ON COLUMN public.inspections.archive_manifest IS 'Manifiesto técnico con tamaño/checksum para reintentos idempotentes antes de borrar Storage';

CREATE TABLE IF NOT EXISTS public.inspection_retention_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inspection_id uuid NOT NULL REFERENCES public.inspections(id) ON DELETE RESTRICT,
  service_id uuid NOT NULL,
  action text NOT NULL CHECK (action IN ('archive', 'purge', 'recover')),
  status text NOT NULL CHECK (status IN ('success', 'failure')),
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS inspection_retention_audit_inspection_idx
  ON public.inspection_retention_audit (inspection_id, created_at DESC);

ALTER TABLE public.inspection_retention_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS inspection_retention_audit_admin_read ON public.inspection_retention_audit;
CREATE POLICY inspection_retention_audit_admin_read
  ON public.inspection_retention_audit
  FOR SELECT TO authenticated
  USING (public.is_admin_user_safe());

REVOKE INSERT, UPDATE, DELETE ON public.inspection_retention_audit FROM anon, authenticated;
GRANT SELECT ON public.inspection_retention_audit TO authenticated;
GRANT ALL ON public.inspection_retention_audit TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.inspection_retention_audit_id_seq TO service_role;

CREATE TABLE IF NOT EXISTS public.inspection_retention_cron_jobs (
  job_name text PRIMARY KEY,
  job_id bigint NOT NULL,
  schedule text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.inspection_retention_cron_jobs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS inspection_retention_cron_jobs_admin_read ON public.inspection_retention_cron_jobs;
CREATE POLICY inspection_retention_cron_jobs_admin_read
  ON public.inspection_retention_cron_jobs
  FOR SELECT TO authenticated
  USING (public.is_admin_user_safe());
REVOKE INSERT, UPDATE, DELETE ON public.inspection_retention_cron_jobs FROM anon, authenticated;
GRANT SELECT ON public.inspection_retention_cron_jobs TO authenticated;
GRANT ALL ON public.inspection_retention_cron_jobs TO service_role;

DO $$
DECLARE
  existing_job record;
  archive_job_id bigint;
  purge_job_id bigint;
BEGIN
  FOR existing_job IN
    SELECT jobid FROM cron.job
    WHERE jobname IN ('archive-inspections-to-r2-monthly', 'purge-cold-inspections-monthly')
  LOOP
    PERFORM cron.unschedule(existing_job.jobid);
  END LOOP;

  archive_job_id := cron.schedule(
    'archive-inspections-to-r2-monthly',
    '30 3 1 * *',
    $cron$
      SELECT net.http_post(
        url := 'https://jqszxljtfuknhuvuheko.supabase.co/functions/v1/archive-inspections-to-r2',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'x-cron-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'CRON_SECRET' LIMIT 1)
        ),
        body := jsonb_build_object('source', 'pg_cron')
      );
    $cron$
  );

  purge_job_id := cron.schedule(
    'purge-cold-inspections-monthly',
    '30 4 2 * *',
    $cron$
      SELECT net.http_post(
        url := 'https://jqszxljtfuknhuvuheko.supabase.co/functions/v1/purge-cold-inspections',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'x-cron-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'CRON_SECRET' LIMIT 1)
        ),
        body := jsonb_build_object('source', 'pg_cron')
      );
    $cron$
  );

  INSERT INTO public.inspection_retention_cron_jobs (job_name, job_id, schedule)
  VALUES
    ('archive-inspections-to-r2-monthly', archive_job_id, '30 3 1 * *'),
    ('purge-cold-inspections-monthly', purge_job_id, '30 4 2 * *')
  ON CONFLICT (job_name) DO UPDATE
    SET job_id = EXCLUDED.job_id,
        schedule = EXCLUDED.schedule,
        created_at = now();
END $$;

